[workspace]
members = [
	"crates/zu-material",
  "crates/zuicon-ant",
  "crates/zuicon-bs",
  "crates/zuicon-material",
  "crates/zuicon-mdl2",
  "crates/zuicon-util",

	"crates/zu-material/examples/*",
]

exclude = [
  "examples",
  "tools",
]

resolver = "2"
