[workspace]
members = [
    "crates/zu",
    #"crates/zuicon-ant",
    #"crates/zuicon-bs",
    "crates/zuicon-material",
    #"crates/zuicon-mdl2",
    "crates/zuicon-util",

    # Docs
    "crates/zu-docs",
]

exclude = [
    "examples",
    "tools",
]

resolver = "2"

[profile.release]
# Slower build, but better optimization
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
