[workspace]
members = [
	"crates/zu-material",
  "crates/zuicon-ant",
  "crates/zuicon-bs",
  "crates/zuicon-material",
  "zuicon-mdl2",
  "zuicon-util",
]

exclude = [
  "examples",
  "tools",
]

resolver = "2"
