[workspace]
members = [
	"crates/zu",
  "crates/zuicon-ant",
  "crates/zuicon-bs",
  "crates/zuicon-material",
  "crates/zuicon-mdl2",
  "crates/zuicon-util",

  # Examples
  "crates/zu-examples",
]

exclude = [
  "examples",
  "tools",
]

resolver = "2"
