[package]
name = "zuicon-ant"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
yew = { version="0.20.0", features=["csr"] }

[build-dependencies]
inflections = "1.1.1"
zuicon-util = { path = "../zuicon-util" }
