[package]
name = "ant-icon-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
zuicon-ant = { path = "../../crates/zuicon-ant" }
wasm-logger = "0.2.0"
yew = { version="0.20.0", features=["csr"] }
