[package]
name = "zu"
version = "0.2.3"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
readme = "README.md"
homepage = "https://github.com/RustVis/zu"
repository = "https://github.com/RustVis/zu"
documentation = "https://docs.rs/zu"
description = "Yew web components, implementing Material Design"
keywords = ["yew", "web", "wasm", "material-design"]
categories = ["gui", "wasm", "web-programming"]
edition = "2021"
license = "Apache-2.0"
publish = true

[dependencies]
log = "0.4.17"
stylist = { version = "0.12.0", default-features = false, features = ["parser", "random", "yew"] }
yew = "0.20.0"
zu-util = { path = "../zu-util", version = "0.1.0" }

[build-dependencies]
rsass = "0.27.0"
