[package]
name = "zu-material"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
log = "0.4.17"
stylist = { version = "0.12.0", features = ["parser", "yew_integration"] }
yew = "0.20.0"

[build-dependencies]
rsass = "0.27.0"