[package]
name = "bs-icon-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wasm-logger = "0.2.0"
yew = { version="0.20.0", features=["csr"] }
zuicon-bs = { path = "../../crates/zuicon-bs" }
